# Generated by Django 5.2.5 on 2025-08-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FreelancerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education", models.TextField(blank=True)),
                ("experience", models.TextField(blank=True)),
                ("skills", models.TextField(blank=True)),
                ("tech_stack", models.TextField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("company_website", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("about", models.TextField(blank=True)),
            ],
        ),
    ]
