# Generated by Django 5.2.5 on 2025-08-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancerprofile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="name",
            field=models.TextField(blank=True),
        ),
    ]
