# Generated by Django 5.2.5 on 2025-08-31 10:36

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_freelancerprofile_dob_freelancerprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancerprofile",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to=profiles.models.resume_upload_path
            ),
        ),
    ]
