# Generated by Django 5.2.5 on 2025-09-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelancerprofile",
            name="skills",
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="freelancers", to="profiles.skill"
            ),
        ),
    ]
