# Generated by Django 5.2.5 on 2025-09-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_remove_freelancerprofile_skills_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelancerprofile",
            name="tech_stack",
        ),
    ]
