# Generated by Django 5.2.5 on 2025-09-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_remove_freelancerprofile_tech_stack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancerprofile",
            name="experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fresher", "Fresher"),
                    ("junior", "Junior (1-2 years)"),
                    ("mid", "Mid-level (3-5 years)"),
                    ("senior", "Senior (5+ years)"),
                    ("expert", "Expert (10+ years)"),
                ],
                max_length=20,
            ),
        ),
    ]
