# Generated by Django 5.2.5 on 2025-09-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_alter_freelancerprofile_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancerprofile",
            name="experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fresher", "Fresher"),
                    ("Junior", "Junior (1-2 years)"),
                    ("Mid", "Mid-level (3-5 years)"),
                    ("Senior", "Senior (5+ years)"),
                    ("Expert", "Expert (10+ years)"),
                ],
                max_length=20,
            ),
        ),
    ]
