# Generated by Django 5.2.5 on 2025-09-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_alter_freelancerprofile_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancerprofile",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("immediate", "Immediate"),
                    ("oneweek", "1 Week"),
                    ("twoweek", "2 Weeks"),
                    ("amonth", "1 Month"),
                    ("openToOffers", "Open to offers"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="expected_salary",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="location",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="phone",
            field=models.TextField(blank=True),
        ),
    ]
