# Generated by Django 5.2.5 on 2025-09-13 19:39

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_freelancerprofile_availability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiterprofile",
            name="compamy_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=profiles.models.logo_upload_path
            ),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="industry",
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="freelancerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
