# Generated by Django 5.2.5 on 2025-09-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0012_recruiterprofile_compamy_logo_recruiterprofile_email_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruiterprofile",
            old_name="compamy_logo",
            new_name="company_logo",
        ),
    ]
