# Generated by Django 5.2.5 on 2025-09-19 07:59

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancerprofile",
            name="profilepic",
            field=models.ImageField(
                blank=True, null=True, upload_to=profiles.models.profilepic_upload_path
            ),
        ),
    ]
