# Generated by Django 5.2.5 on 2025-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        ("profiles", "0006_remove_freelancerprofile_skills_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="tech_stack",
        ),
        migrations.AddField(
            model_name="job",
            name="tech_stack",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="profiles.skill"
            ),
        ),
    ]
