# Generated by Django 5.2.5 on 2025-09-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_remove_job_tech_stack_job_tech_stack"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="cover_letter",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/resumes/"
            ),
        ),
    ]
