# Generated by Django 5.2.5 on 2025-09-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_application_cover_letter_application_resume"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="tech_stack",
            new_name="skills",
        ),
    ]
