# Generated by Django 5.2.5 on 2025-09-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_rename_tech_stack_job_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("inoffice", "In-Office"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
