# Generated by Django 5.2.5 on 2025-09-09 07:43

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=jobs.models.picture_upload_path
            ),
        ),
    ]
