# Generated by Django 5.2.5 on 2025-09-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_job_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="key_responsibilities",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="job",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("inoffice", "In-Office"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="requirements",
            field=models.TextField(default="N/A"),
        ),
    ]
