# Generated by Django 5.2.5 on 2025-09-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_job_key_responsibilities_job_work_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="key_responsibilities",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="requirements",
            field=models.TextField(),
        ),
    ]
